In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix, f1_score, accuracy_score

In [2]:
dataset=pd.read_csv('winequalityN.csv')
dataset=pd.get_dummies(dataset)
dataset.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  type_red  type_white  
0      8.8        6         0           1  
1      9.5        6         0           1  
2     10.1        6         0           1  
3      9.9        6         0           1  
4      9.9        6         0           1

In [3]:
dataset = dataset.dropna()
dataset

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0             0.270         0.36            20.7      0.045   
1               6.3             0.300         0.34             1.6      0.049   
2               8.1             0.280         0.40             6.9      0.050   
3               7.2             0.230         0.32             8.5      0.058   
4               7.2             0.230         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
6491            6.8             0.620         0.08             1.9      0.068   
6492            6.2             0.600         0.08             2.0      0.090   
6494            6.3             0.510         0.13             2.3      0.076   
6495            5.9             0.645         0.12             2.0      0.075   
6496            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
6491                 28.0                  38.0  0.99651  3.42       0.82   
6492                 32.0                  44.0  0.99490  3.45       0.58   
6494                 29.0                  40.0  0.99574  3.42       0.75   
6495                 32.0                  44.0  0.99547  3.57       0.71   
6496                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  type_red  type_white  
0         8.8        6         0           1  
1         9.5        6         0           1  
2        10.1        6         0           1  
3         9.9        6         0           1  
4         9.9        6         0           1  
...       ...      ...       ...         ...  
6491      9.5        6         1           0  
6492     10.5        5         1           0  
6494     11.0        6         1           0  
6495     10.2        5         1           0  
6496     11.0        6         1           0  

[6463 rows x 14 columns]

In [4]:
x = dataset.drop(["quality"],axis=1,inplace=False)
x

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0             0.270         0.36            20.7      0.045   
1               6.3             0.300         0.34             1.6      0.049   
2               8.1             0.280         0.40             6.9      0.050   
3               7.2             0.230         0.32             8.5      0.058   
4               7.2             0.230         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
6491            6.8             0.620         0.08             1.9      0.068   
6492            6.2             0.600         0.08             2.0      0.090   
6494            6.3             0.510         0.13             2.3      0.076   
6495            5.9             0.645         0.12             2.0      0.075   
6496            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
6491                 28.0                  38.0  0.99651  3.42       0.82   
6492                 32.0                  44.0  0.99490  3.45       0.58   
6494                 29.0                  40.0  0.99574  3.42       0.75   
6495                 32.0                  44.0  0.99547  3.57       0.71   
6496                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  type_red  type_white  
0         8.8         0           1  
1         9.5         0           1  
2        10.1         0           1  
3         9.9         0           1  
4         9.9         0           1  
...       ...       ...         ...  
6491      9.5         1           0  
6492     10.5         1           0  
6494     11.0         1           0  
6495     10.2         1           0  
6496     11.0         1           0  

[6463 rows x 13 columns]

In [5]:
bins = (2, 6, 9)
group_names = ['bad', 'good']
dataset['quality'] = pd.cut(dataset['quality'], bins = bins, labels = group_names)
label_quality = LabelEncoder()
dataset['quality'] = label_quality.fit_transform(dataset['quality'])
dataset['quality'].value_counts()
y = dataset['quality']
y.head()

0    0
1    0
2    0
3    0
4    0
Name: quality, dtype: int32

In [6]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=0)
print(len(x))
print(len(x_train))
print(len(x_test))

6463
4524
1939


In [7]:
from sklearn.neighbors import KNeighborsClassifier
kn = KNeighborsClassifier()
kn.fit(x_train, y_train)
knpreds = kn.predict(x_test)
print(f"KNN Classifier\n\n {classification_report(y_test,knpreds)}")
cm=confusion_matrix(y_test,knpreds)
print(cm)
print(accuracy_score(y_test,knpreds))
print(f1_score(y_test,knpreds))

KNN Classifier

               precision    recall  f1-score   support

           0       0.86      0.92      0.89      1568
           1       0.51      0.35      0.41       371

    accuracy                           0.81      1939
   macro avg       0.68      0.63      0.65      1939
weighted avg       0.79      0.81      0.80      1939

[[1442  126]
 [ 242  129]]
0.8102114492006188
0.41214057507987223


In [8]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier()
RF.fit(x_train, y_train)
RFpreds = RF.predict(x_test)
print(f"Random Forest\n\n {classification_report(y_test,RFpreds)}")
cm=confusion_matrix(y_test,RFpreds)
print(cm)
print(accuracy_score(y_test,RFpreds))
print(f1_score(y_test,RFpreds))

Random Forest

               precision    recall  f1-score   support

           0       0.90      0.97      0.93      1568
           1       0.82      0.53      0.64       371

    accuracy                           0.89      1939
   macro avg       0.86      0.75      0.79      1939
weighted avg       0.88      0.89      0.88      1939

[[1524   44]
 [ 175  196]]
0.887055183084064
0.641571194762684


In [9]:
from sklearn.tree import DecisionTreeClassifier
DT = DecisionTreeClassifier()
DT.fit(x_train, y_train)
DTpreds = DT.predict(x_test)
print(f"Decision Tree\n\n {classification_report(y_test,DTpreds)}")
cm=confusion_matrix(y_test,DTpreds)
print(cm)
print(accuracy_score(y_test,DTpreds))
print(f1_score(y_test,DTpreds))

Decision Tree

               precision    recall  f1-score   support

           0       0.90      0.88      0.89      1568
           1       0.55      0.60      0.57       371

    accuracy                           0.83      1939
   macro avg       0.72      0.74      0.73      1939
weighted avg       0.83      0.83      0.83      1939

[[1384  184]
 [ 150  221]]
0.8277462609592573
0.5695876288659794


In [10]:
from sklearn.naive_bayes import GaussianNB
gn = GaussianNB()
gn.fit(x_train, y_train)
gnpreds = gn.predict(x_test)
print(f"Gaussian Naive Bayes\n\n {classification_report(y_test,gnpreds)}")
cm=confusion_matrix(y_test,gnpreds)
print(cm)
print(accuracy_score(y_test,gnpreds))
print(f1_score(y_test,gnpreds))

Gaussian Naive Bayes

               precision    recall  f1-score   support

           0       0.91      0.73      0.81      1568
           1       0.38      0.70      0.49       371

    accuracy                           0.73      1939
   macro avg       0.65      0.71      0.65      1939
weighted avg       0.81      0.73      0.75      1939

[[1149  419]
 [ 113  258]]
0.7256317689530686
0.4923664122137405


In [11]:
from sklearn.linear_model import LogisticRegression
X_train = StandardScaler().fit_transform(x_train)
X_test = StandardScaler().fit_transform(x_test)
LR = LogisticRegression()
LR.fit(X_train, y_train)
LRpreds = LR.predict(X_test)
print(f"Logistic Regression\n\n {classification_report(y_test,LRpreds)}")
cm=confusion_matrix(y_test,LRpreds)
print(cm)
print(accuracy_score(y_test,LRpreds))
print(f1_score(y_test,LRpreds))

Logistic Regression

               precision    recall  f1-score   support

           0       0.84      0.95      0.89      1568
           1       0.54      0.24      0.33       371

    accuracy                           0.82      1939
   macro avg       0.69      0.60      0.61      1939
weighted avg       0.78      0.82      0.79      1939

[[1493   75]
 [ 282   89]]
0.8158844765342961
0.33271028037383177
